name: Backend CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    
    # Backend Build
    - name: Use Node.js ${{ matrix.node-version }} for Backend
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Cache Backend Node Modules
      uses: actions/cache@v3
      with:
        path: backend/node_modules
        key: ${{ runner.os }}-backend-${{ hashFiles('backend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-backend-
          
    - name: Install Backend Dependencies
      run: |
        cd backend
        npm ci
        

    - name: Build Backend
      run: |
        cd backend
        npm run build --if-present
        
    # - name: Test Backend
    #   run: |
    #     cd backend
    #     npm test
        
